[project]
name = "aei"
version = "0.1.0"
description = "Building out AEI intelligence"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django==5.2",
    "openai>=1.74.0",
    "pypdfium2>=4.30.1",
    "python-pptx>=1.0.2",
]
