# Generated by Django 5.2 on 2025-04-16 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EXCEL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="pdf_files/")),
                ("name", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="PPTX",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="pptx_files/")),
                ("name", models.CharField(max_length=255)),
                ("context", models.CharField(max_length=2000)),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="WORD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="word_files/")),
                ("name", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="IMAGE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("file", models.FileField(upload_to="image_files/")),
                ("context", models.CharField(max_length=2000)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SLIDE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="slide_images/")),
                ("text", models.TextField()),
                ("context", models.CharField(max_length=2000)),
                (
                    "pptx",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applibrary.pptx",
                    ),
                ),
            ],
        ),
    ]
